[package]
name = "mirror_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "vrv_host"
path = "src/bin/vrv_host.rs"

[[bin]]
name = "vrv_signal"
path = "src/bin/vrv_signal.rs"

[[bin]]
name = "vrv_desk"
path = "src/bin/vrv_desk.rs"

[[bin]]
name = "vrv_setup"
path = "src/bin/vrv_setup.rs"

[[bin]]
name = "vrv_service"
path = "src/bin/vrv_service.rs"


[dependencies]
flutter_rust_bridge = "=2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
sha2 = "0.10"
rand = "0.8"
socket2 = "0.5"
tokio = { version = "1.36", features = ["full"] }
hex = "0.4"
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
fast_image_resize = "6.1.0"
tokio-tungstenite = { version = "0.30.0", features = ["connect"] }
futures-util = "0.3.34"
opus = "0.4.0"
openh264 = { version = "0.9.8", features = ["source"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_Media_Audio",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
    "Win32_System_LibraryLoader",
    "Win32_System_Services",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Pipes",
    "Win32_UI_Shell",
    "Win32_System_Registry",
    "Win32_System_StationsAndDesktops",
]
